let books = [
  {
    titre: "Le Petit Prince",
    nbPages: 96,
    extrait: "On ne voit bien qu'avec le cœur.",
    resume:
      "Un aviateur échoue dans le désert et rencontre un petit prince venu d'une autre planète.",
    anneeEdition: "1943-04-06",
    _imageCouverture: "uploads/1741706731356.jpg",
    editeur_fk: 1,
    categorie_fk: 1,
    auteur_fk: 1,
    user_fk: 1,
  },
  {
    titre: "1984",
    nbPages: 328,
    extrait: "Big Brother vous regarde.",
    resume:
      "Dans une société totalitaire, un homme tente de se rebeller contre le contrôle du gouvernement.",
    anneeEdition: "1949-06-08",
    _imageCouverture: "uploads/1746002260259.jpg",
    editeur_fk: 2,
    categorie_fk: 2,
    auteur_fk: 2,
    user_fk: 1,
  },
  {
    titre: "Harry Potter à l'école des sorciers",
    nbPages: 309,
    extrait: "Tu es un sorcier, Harry.",
    resume:
      "Un jeune garçon découvre qu'il est sorcier et rejoint l'école de magie Poudlard.",
    anneeEdition: "1997-06-26",
    _imageCouverture: "uploads/1746002365406.jpg",
    editeur_fk: 3,
    categorie_fk: 3,
    auteur_fk: 3,
    user_fk: 3,
  },
  {
    titre: "Les Misérables",
    nbPages: 1463,
    extrait: "Aimer, c'est agir.",
    resume:
      "L'histoire de Jean Valjean, un ancien forçat en quête de rédemption.",
    anneeEdition: "1862-04-03",
    _imageCouverture: "uploads/1746002397208.jpg",
    editeur_fk: 4,
    categorie_fk: 4,
    auteur_fk: 4,
    user_fk: 2,
  },
  {
    titre: "Le Seigneur des Anneaux",
    nbPages: 1216,
    extrait: "Un anneau pour les gouverner tous.",
    resume:
      "Un groupe de héros doit détruire un anneau maléfique pour sauver le monde.",
    anneeEdition: "1954-07-29",
    _imageCouverture: "uploads/1746002472886.jpg",
    editeur_fk: 5,
    categorie_fk: 3,
    auteur_fk: 5,
    user_fk: 1,
  },
  {
    titre: "Orgueil et Préjugés",
    nbPages: 432,
    extrait: "Il est une vérité universellement reconnue...",
    resume:
      "Une histoire d'amour et de malentendus dans l'Angleterre du XIXe siècle.",
    anneeEdition: "1813-01-28",
    _imageCouverture: "uploads/1746002498839.jpg",
    editeur_fk: 6,
    categorie_fk: 5,
    auteur_fk: 6,
    user_fk: 1,
  },
  {
    titre: "Crime et Châtiment",
    nbPages: 671,
    extrait: "Le crime appelle le châtiment.",
    resume: "Un jeune homme commet un meurtre et lutte avec sa conscience.",
    anneeEdition: "1866-01-01",
    _imageCouverture: "uploads/1746002543536.jpeg",
    editeur_fk: 7,
    categorie_fk: 4,
    auteur_fk: 7,
    user_fk: 1,
  },
  {
    titre: "Alice au pays des merveilles",
    nbPages: 272,
    extrait: "Curiouser and curiouser!",
    resume:
      "Une jeune fille explore un monde fantastique peuplé de créatures étranges.",
    anneeEdition: "1865-11-26",
    _imageCouverture: "uploads/1746002609852.jpg",
    editeur_fk: 8,
    categorie_fk: 1,
    auteur_fk: 8,
    user_fk: 2,
  },
  {
    titre: "Moby Dick",
    nbPages: 720,
    extrait: "Appelez-moi Ismaël.",
    resume: "Un capitaine obsédé poursuit une baleine blanche.",
    anneeEdition: "1851-10-18",
    _imageCouverture: "uploads/1746002655586.jpg",
    editeur_fk: 9,
    categorie_fk: 6,
    auteur_fk: 9,
    user_fk: 3,
  },
  {
    titre: "Don Quichotte",
    nbPages: 863,
    extrait: "À l'attaque, moulins à vent!",
    resume: "Un homme se prend pour un chevalier et part à l'aventure.",
    anneeEdition: "1605-01-16",
    _imageCouverture: "uploads/1746002682528.jpg",
    editeur_fk: 10,
    categorie_fk: 5,
    auteur_fk: 10,
    user_fk: 3,
  },
  {
    titre: "Le Nom de la Rose",
    nbPages: 552,
    extrait: "Le rire tue la peur.",
    resume:
      "Une enquête sur des meurtres mystérieux dans une abbaye médiévale.",
    anneeEdition: "1980-01-01",
    _imageCouverture: "uploads/1746002703655.jpg",
    editeur_fk: 11,
    categorie_fk: 7,
    auteur_fk: 11,
    user_fk: 2,
  },
  {
    titre: "La Métamorphose",
    nbPages: 120,
    extrait:
      "Un matin, Gregor Samsa se réveilla transformé en un insecte monstrueux.",
    resume: "Un homme se réveille un jour métamorphosé en un énorme insecte.",
    anneeEdition: "1915-01-01",
    _imageCouverture: "uploads/1746002721177.jpg",
    editeur_fk: 12,
    categorie_fk: 8,
    auteur_fk: 12,
    user_fk: 3,
  },
  {
    titre: "Fahrenheit 451",
    nbPages: 256,
    extrait: "Brûler, c'est un plaisir.",
    resume:
      "Dans un futur où les livres sont interdits, un pompier brûleur de livres remet en question son rôle.",
    anneeEdition: "1953-10-19",
    _imageCouverture: "uploads/1746002735601.jpg",
    editeur_fk: 13,
    categorie_fk: 2,
    auteur_fk: 13,
    user_fk: 2,
  },
  {
    titre: "L'Étranger",
    nbPages: 185,
    extrait: "Aujourd'hui, maman est morte.",
    resume:
      "Un homme indifférent à la société commet un meurtre et fait face à son procès.",
    anneeEdition: "1942-05-01",
    _imageCouverture: "uploads/1746002786334.jpg",
    editeur_fk: 14,
    categorie_fk: 8,
    auteur_fk: 14,
    user_fk: 1,
  },
  {
    titre: "Le Comte de Monte-Cristo",
    nbPages: 1276,
    extrait: "La vengeance est un plat qui se mange froid.",
    resume: "Un homme emprisonné à tort s'échappe et prépare sa vengeance.",
    anneeEdition: "1844-01-28",
    _imageCouverture: "uploads/1746002803095.jpg",
    editeur_fk: 15,
    categorie_fk: 4,
    auteur_fk: 15,
    user_fk: 1,
  },
  {
    titre: "L'Odyssée",
    nbPages: 541,
    extrait: "Chante, ô muse, la colère d'Ulysse.",
    resume:
      "L'épopée du héros grec Ulysse tentant de retourner chez lui après la guerre de Troie.",
    anneeEdition: "-800-01-01",
    _imageCouverture: "uploads/1746002822127.jpg",
    editeur_fk: 16,
    categorie_fk: 9,
    auteur_fk: 16,
    user_fk: 1,
  },
  {
    titre: "Frankenstein",
    nbPages: 280,
    extrait: "C'est vivant !",
    resume: "Un scientifique crée une créature qui échappe à son contrôle.",
    anneeEdition: "1818-01-01",
    _imageCouverture: "uploads/1746002942749.jpg",
    editeur_fk: 17,
    categorie_fk: 10,
    auteur_fk: 17,
    user_fk: 2,
  },
  {
    titre: "Le Rouge et le Noir",
    nbPages: 576,
    extrait: "Une ambition démesurée mène souvent à la chute.",
    resume:
      "L'ascension sociale d'un jeune homme ambitieux dans une société rigide.",
    anneeEdition: "1830-11-01",
    _imageCouverture: "uploads/1746003019549.jpg",
    editeur_fk: 18,
    categorie_fk: 5,
    auteur_fk: 18,
    user_fk: 2,
  },
  {
    titre: "Germinal",
    nbPages: 592,
    extrait: "La mine, c'est la mort lente.",
    resume: "Les luttes des mineurs dans le nord de la France au XIXe siècle.",
    anneeEdition: "1885-03-01",
    _imageCouverture: "uploads/1746003045225.jpg",
    editeur_fk: 19,
    categorie_fk: 4,
    auteur_fk: 19,
    user_fk: 3,
  },
  {
    titre: "Voyage au centre de la Terre",
    nbPages: 303,
    extrait: "Descendons dans les entrailles de la Terre.",
    resume: "Un scientifique et son neveu explorent le cœur de notre planète.",
    anneeEdition: "1864-11-25",
    _imageCouverture: "uploads/1746003063888.jpg",
    editeur_fk: 20,
    categorie_fk: 3,
    auteur_fk: 20,
    user_fk: 1,
  },
  {
    titre: "Le Château",
    nbPages: 450,
    extrait: "Il aperçut la silhouette d'un homme qu'il n'avait jamais vu.",
    resume:
      "Le Château de Kafka suit K., un homme en quête de son propre sens de l'existence dans un monde absurde et oppressant.",
    anneeEdition: "1926-05-12",
    _imageCouverture: "uploads/1746540565096.jpg",
    editeur_fk: 7,
    categorie_fk: 1,
    auteur_fk: 12,
    user_fk: 1,
  },
  {
    titre: "Les Aventures de Tom Sawyer",
    nbPages: 300,
    extrait: "Tom, dis-moi, as-tu promis de ne rien dire à personne ?",
    resume:
      "Tom Sawyer vit des aventures avec son ami Huck, luttant contre l'autorité et explorant l'Amérique du XIXe siècle.",
    anneeEdition: "1876-06-01",
    _imageCouverture: "uploads/Les-aventures-de-Tom-Sawyerl.jpg",
    editeur_fk: 6,
    categorie_fk: 3,
    auteur_fk: 8,
    user_fk: 1,
  },
  {
    titre: "Les Voyages de Gulliver",
    nbPages: 384,
    extrait: "Je suis le capitaine de ce navire.",
    resume:
      "Gulliver explore des îles peuplées de créatures étranges et dénonce les faiblesses humaines.",
    anneeEdition: "1726-10-28",
    _imageCouverture: "uploads/Les-voyages-de-Gulliver-Texte-Abrege.jpg",
    editeur_fk: 2,
    categorie_fk: 1,
    auteur_fk: 9,
    user_fk: 1,
  },
  {
    titre: "Le Parfum",
    nbPages: 431,
    extrait: "Il se leva, écouta, puis s'avança.",
    resume:
      "Grenouille, un homme sans odeur, est obsédé par l'idée de créer le parfum parfait, au prix de crimes.",
    anneeEdition: "1985-06-18",
    _imageCouverture: "uploads/le-parfum.jpg",
    editeur_fk: 4,
    categorie_fk: 6,
    auteur_fk: 10,
    user_fk: 1,
  },
  {
    titre: "La Peste",
    nbPages: 468,
    extrait: "Le cœur de la ville battait au rythme de l'épidémie.",
    resume:
      "La Peste dépeint une ville frappée par une épidémie, et les réactions humaines face à la souffrance et à la mort.",
    anneeEdition: "1947-01-01",
    _imageCouverture: "uploads/la-peste.jpg",
    editeur_fk: 5,
    categorie_fk: 4,
    auteur_fk: 13,
    user_fk: 1,
  },
  {
    titre: "Les Raisins de la colère",
    nbPages: 464,
    extrait: "Tom Joad marcha lentement, la tête basse.",
    resume:
      "Les Raisins de la colère suit les Joad, une famille fuyant la misère, luttant pour survivre pendant la Grande Dépression.",
    anneeEdition: "1939-04-14",
    _imageCouverture: "uploads/les-raisins-de-la-colere.jpg",
    editeur_fk: 3,
    categorie_fk: 6,
    auteur_fk: 14,
    user_fk: 1,
  },
  {
    titre: "Bel-Ami",
    nbPages: 432,
    extrait: "Georges Duroy se tenait dans l'ombre.",
    resume:
      "Georges Duroy, un homme sans scrupules, gravit les échelons de la société parisienne avec charme et manipulation.",
    anneeEdition: "1885-01-16",
    _imageCouverture: "uploads/Bel-Ami.jpg",
    editeur_fk: 8,
    categorie_fk: 3,
    auteur_fk: 18,
    user_fk: 1,
  },
  {
    titre: "L'Alchimiste",
    nbPages: 208,
    extrait: "Les gens qui rêvent accomplissent des miracles.",
    resume:
      "L'Alchimiste raconte l'histoire de Santiago, un jeune berger qui part à la recherche d'un trésor et découvre le sens de la vie.",
    anneeEdition: "1988-11-01",
    _imageCouverture: "uploads/L-alchimiste.jpg",
    editeur_fk: 9,
    categorie_fk: 6,
    auteur_fk: 15,
    user_fk: 1,
  },
  {
    titre: "La Ferme des animaux",
    nbPages: 112,
    extrait:
      "Tous les animaux sont égaux, mais certains sont plus égaux que d'autres.",
    resume:
      "Les animaux de la ferme se révoltent contre leurs maîtres, mais se retrouvent sous la tyrannie d'autres animaux.",
    anneeEdition: "1945-08-17",
    _imageCouverture: "uploads/La-ferme-des-animaux.jpg",
    editeur_fk: 6,
    categorie_fk: 6,
    auteur_fk: 10,
    user_fk: 1,
  },
  {
    titre: "Jane Eyre",
    nbPages: 504,
    extrait: "Il me regarda et je sus qu'il m'avait comprise.",
    resume:
      "Jane Eyre est l'histoire d'une orpheline qui trouve l'amour avec un homme mystérieux et torturé.",
    anneeEdition: "1847-10-16",
    _imageCouverture: "uploads/Jane-Eyre.jpg",
    editeur_fk: 7,
    categorie_fk: 8,
    auteur_fk: 5,
    user_fk: 1,
  },
  {
    titre: "Dracula",
    nbPages: 420,
    extrait: "Il se tourna soudainement et se jeta sur moi.",
    resume:
      "Dracula raconte l'histoire du comte vampire et de sa quête pour semer la terreur en Angleterre.",
    anneeEdition: "1897-05-26",
    _imageCouverture: "uploads/dracula.jpg",
    editeur_fk: 10,
    categorie_fk: 3,
    auteur_fk: 7,
    user_fk: 1,
  },
  {
    titre: "Le Dernier Jour d'un Condamné",
    nbPages: 256,
    extrait:
      "Ce qui est fait est fait, mais ce qui est à venir ne dépend que de vous.",
    resume:
      "Un homme attend son exécution, se battant avec ses pensées et le destin qui l'attend.",
    anneeEdition: "1829-01-01",
    _imageCouverture: "uploads/Dernier-jour-d-un-condamne.jpg",
    editeur_fk: 2,
    categorie_fk: 4,
    auteur_fk: 3,
    user_fk: 1,
  },
  {
    titre: "Madame Bovary",
    nbPages: 416,
    extrait: "Elle ne savait pas vivre sans passion.",
    resume:
      "Madame Bovary raconte l'histoire d'une femme insatisfaite de sa vie provinciale, en quête d'aventures et d'émotions.",
    anneeEdition: "1857-01-01",
    _imageCouverture: "uploads/Madame-Bovary.jpg",
    editeur_fk: 11,
    categorie_fk: 8,
    auteur_fk: 18,
    user_fk: 1,
  },
  {
    titre: "Les Liaisons Dangereuses",
    nbPages: 500,
    extrait: "La véritable noblesse consiste à se faire aimer.",
    resume:
      "Un jeu cruel de manipulations et de séduction entre les membres de la noblesse française du XVIIIe siècle.",
    anneeEdition: "1782-04-01",
    _imageCouverture: "uploads/les-liaisons-dangereuses.jpg",
    editeur_fk: 9,
    categorie_fk: 3,
    auteur_fk: 18,
    user_fk: 1,
  },
  {
    titre: "Le Cancre",
    nbPages: 15,
    extrait: "Je suis ce que je suis.",
    resume:
      "Un poème emblématique de Jacques Prévert sur l’enfance, la rébellion et l’innocence.",
    anneeEdition: "1946-01-01",
    _imageCouverture: "uploads/le-cancre.jpg",
    editeur_fk: 12,
    categorie_fk: 10,
    auteur_fk: 11,
    user_fk: 1,
  },
  {
    titre: "La Chanson de Roland",
    nbPages: 128,
    extrait: "Ô Roland, si tu savais !",
    resume:
      "Un des plus célèbres poèmes épiques du Moyen Âge qui raconte la bataille de Roncevaux.",
    anneeEdition: "1100-01-01",
    _imageCouverture: "uploads/la-chanson-de-roland.jpg",
    editeur_fk: 13,
    categorie_fk: 10,
    auteur_fk: 15,
    user_fk: 1,
  },
  {
    titre: "Le Livre de ma mère",
    nbPages: 150,
    extrait: "C’était une mère sans pareil.",
    resume:
      "Un poème en prose de Albert Cohen sur la mémoire et l’amour d’une mère.",
    anneeEdition: "1973-01-01",
    _imageCouverture: "uploads/Le-Livre-de-ma-mere.jpg",
    editeur_fk: 14,
    categorie_fk: 10,
    auteur_fk: 11,
    user_fk: 1,
  },
  {
    titre: "Le Mythe de Sisyphe",
    nbPages: 288,
    extrait:
      "Le seul problème philosophique véritablement sérieux, c’est le suicide.",
    resume:
      "Essai d'Albert Camus sur l'absurde, où il explore la lutte de l'homme contre le sens de la vie.",
    anneeEdition: "1942-01-01",
    _imageCouverture: "uploads/le-mythe-de-sisyphe.jpg",
    editeur_fk: 16,
    categorie_fk: 9,
    auteur_fk: 13,
    user_fk: 1,
  },
  {
    titre: "Discours de la méthode",
    nbPages: 192,
    extrait: "Je pense, donc je suis.",
    resume:
      "Un des textes fondateurs de la philosophie moderne de René Descartes, expliquant sa méthode pour parvenir à la vérité.",
    anneeEdition: "1637-01-01",
    _imageCouverture: "uploads/Discours-de-la-methode.jpg",
    editeur_fk: 14,
    categorie_fk: 9,
    auteur_fk: 12,
    user_fk: 1,
  },
  {
    titre: "Le Deuxième Sexe",
    nbPages: 800,
    extrait: "On ne naît pas femme, on le devient.",
    resume:
      "Essai fondamental de Simone de Beauvoir sur la condition féminine et les structures sociales oppressives.",
    anneeEdition: "1949-01-01",
    _imageCouverture: "uploads/le-deuxieme-sexe.jpg",
    editeur_fk: 18,
    categorie_fk: 9,
    auteur_fk: 13,
    user_fk: 1,
  },
];
export { books };
