let authors = [
  { nom: "Hugo", prenom: "Victor" },
  { nom: "Orwell", prenom: "George" },
  { nom: "Rowling", prenom: "J.K." },
  { nom: "Tolkien", prenom: "J.R.R." },
  { nom: "Austen", prenom: "Jane" },
  { nom: "Dostoïevski", prenom: "Fiodor" },
  { nom: "Carroll", prenom: "Lewis" },
  { nom: "Melville", prenom: "Herman" },
  { nom: "Cervantes", prenom: "Miguel de" },
  { nom: "Eco", prenom: "Umberto" },
  { nom: "Kafka", prenom: "Franz" },
  { nom: "Bradbury", prenom: "Ray" },
  { nom: "Camus", prenom: "Albert" },
  { nom: "Dumas", prenom: "Alexandre" },
  { nom: "Homère", prenom: "-" },
  { nom: "Shelley", prenom: "Mary" },
  { nom: "Stendhal", prenom: "Henri" },
  { nom: "Zola", prenom: "Émile" },
  { nom: "Verne", prenom: "Jules" },
  { nom: "Proust", prenom: "Marcel" },
];
export { authors };
